image: node:9

stages:
  - test
  - release

test <%= type %>:
  stage: test
  before_script:
    - npm i -g npm
    - npm <% if (type === 'application') { %>ci<% } else { %>install<% } %>
  script:
    - npm test
  coverage: /All files\s*\|\s*([\d\.]+)/
  except:
    - tags

release <%= type %>:
  stage: release
  before_script:
    - npm <% if (type === 'application') { %>ci<% } else { %>install<% } %>
    - npm run build
  script:
    - npm run semantic-release
  only:
    - master
